apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.app_name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{values.app_name}}
  template:
    metadata:
      labels:
        app: ${{values.app_name}}
    spec:
      containers:
      - name: app
        image: python:3.9
        command: ["python", "app.py"]
